
-- TABLE DEFINITION
-- Run this in the Supabase SQL Editor (https://supabase.com/dashboard/project/ebxcirakgqzefjfdxvao/sql/new)

CREATE TABLE IF NOT EXISTS public.student_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id TEXT NOT NULL,
    date DATE NOT NULL,
    tasks JSONB DEFAULT '[]'::jsonb,
    audio_guides JSONB DEFAULT '[]'::jsonb,
    wisdom JSONB DEFAULT NULL,
    progress_percent INT DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- This constraint is REQUIRED for the app's .upsert() function to work.
    -- It ensures that for every (Student + Date) pair, there is only one record.
    UNIQUE (student_id, date)
);

-- SECURITY
-- Enable Row Level Security (RLS)
ALTER TABLE public.student_progress ENABLE ROW LEVEL SECURITY;

-- POLICY: Allow all operations (Insert, Update, Select) for users with the Public API Key
-- This is suitable for an 'anon' key setup where you don't have user authentication enabled yet.
CREATE POLICY "Allow public access for anon" 
ON public.student_progress
FOR ALL 
TO anon 
USING (true) 
WITH CHECK (true);

-- INDEXING (Optional but recommended for performance as the database grows)
CREATE INDEX idx_student_date ON public.student_progress (student_id, date);
